### ISSUE TITLE
It's fork https://github.com/trntv/yii2-starter-kit ) 

### ISSUE THREAD

**Issue by sonrac** [dungphanxuan/yii2-starter-kit-lite#12]
Original project is https://github.com/trntv/yii2-starter-kit
You are adding only api client, project structure and all components based on yii2-starter-kit ))) 
Add donate block for terentev at least)))

**Comment by dungphanxuan** [comment]
Yes, as i said. that i custome add add more feature.
You can see feature:
 - Single Domain
 - API Application
- Custome more backend feature
and more

![image](https://cloud.githubusercontent.com/assets/10725732/23088868/c71035a2-f5b3-11e6-8760-4e65e9ebb281.png)
